-- AlterTable
ALTER TABLE "Order" ADD COLUMN "code2" TEXT;
ALTER TABLE "Order" ADD COLUMN "code3" TEXT;
ALTER TABLE "Order" ADD COLUMN "code4" TEXT;
ALTER TABLE "Order" ADD COLUMN "cost2" TEXT;
ALTER TABLE "Order" ADD COLUMN "cost3" TEXT;
ALTER TABLE "Order" ADD COLUMN "cost4" TEXT;
ALTER TABLE "Order" ADD COLUMN "description2" TEXT;
ALTER TABLE "Order" ADD COLUMN "description3" TEXT;
ALTER TABLE "Order" ADD COLUMN "description4" TEXT;
ALTER TABLE "Order" ADD COLUMN "qnt2" TEXT;
ALTER TABLE "Order" ADD COLUMN "qnt3" TEXT;
ALTER TABLE "Order" ADD COLUMN "qnt4" TEXT;
ALTER TABLE "Order" ADD COLUMN "size2" TEXT;
ALTER TABLE "Order" ADD COLUMN "size3" TEXT;
ALTER TABLE "Order" ADD COLUMN "size4" TEXT;
